export interface AnalystStatCard {
  label: string;
  value: string;
  change: string;
  trend: 'up' | 'down';
}

export interface ContributingFactor {
  id: number;
  factor: string;
  impact: 'High' | 'Medium' | 'Low';
  change: string;
  details: string;
}

export interface SalesDropProduct {
  id: number;
  product: string;
  salesLastWeek: string;
  change: string;
}

export const ANALYST_SUGGESTIONS = [
  'How is my revenue this month?',
  'Which products are top sellers?',
  'Why did sales drop on Sunday?',
  'Compare conversion rate vs last month',
];

export const MOCK_ANALYST_RESULT = {
  summary: "Your store's overall revenue increased by 18.6% over the last 30 days, driven primarily by strong performance in Electronics (+24.2%) and higher average order values during mid-week promotional campaigns. However, sales dropped by 12.4% on weekends due to lower conversion rates on mobile devices.",
  statCards: [
    { label: 'Sales Last Week', value: '$6,450.20', change: '+14.2%', trend: 'up' },
    { label: 'Sales Prev. Week', value: '$5,648.00', change: '+8.5%', trend: 'up' },
    { label: 'Order Count Last Wk', value: '312', change: '+10.5%', trend: 'up' },
    { label: 'Order Count Prev. Wk', value: '282', change: '+4.2%', trend: 'up' },
    { label: 'AOV Last Week', value: '$20.67', change: '+3.3%', trend: 'up' },
  ] as AnalystStatCard[],
  salesTrend4Weeks: [
    { week: 'Week 1', revenue: 4800 },
    { week: 'Week 2', revenue: 5400 },
    { week: 'Week 3', revenue: 5648 },
    { week: 'Week 4', revenue: 6450 },
  ],
  orderTrend4Weeks: [
    { week: 'Week 1', orders: 240 },
    { week: 'Week 2', orders: 270 },
    { week: 'Week 3', orders: 282 },
    { week: 'Week 4', orders: 312 },
  ],
  contributingFactors: [
    { id: 1, factor: 'Electronics Promotion', impact: 'High', change: '+24.2%', details: 'Flash sale campaign boosted Wireless Headphones sales by 35%' },
    { id: 2, factor: 'Mid-week Cart Bundling', impact: 'Medium', change: '+15.8%', details: 'Average units per order increased from 1.4 to 1.8' },
    { id: 3, factor: 'Weekend Mobile Drop', impact: 'Low', change: '-12.4%', details: 'Slower checkout experience reported on mobile WebKit browser' },
  ] as ContributingFactor[],
  salesDropProducts: [
    { id: 1, product: 'USB-C Cable Pack', salesLastWeek: '$180.00', change: '-18.5%' },
    { id: 2, product: 'Bluetooth Adapter', salesLastWeek: '$120.00', change: '-14.2%' },
    { id: 3, product: 'Desk Lamp LED', salesLastWeek: '$95.00', change: '-9.8%' },
  ] as SalesDropProduct[],
  keyInsights: [
    'Electronics remains your primary revenue engine generating 40.1% of total GMV.',
    'AOV peaked at $21.20 on Thursday due to bundle recommendations at checkout.',
    'Mobile traffic conversion is 1.2% lower than desktop; optimizing checkout mobile UI could unlock ~$1,800/mo.',
    'Stock levels for Smart Watch are running low (< 15 units remaining).'
  ],
  explanation: 'This analysis was generated by cross-referencing your store sales data, customer web sessions, order conversion funnels, and benchmark marketplace distributions.',
};

export const QUERY_HISTORY = [
  { id: 'q-1', question: 'How is my revenue this month?', timestamp: 'Today, 02:14 PM' },
  { id: 'q-2', question: 'Which products are top sellers?', timestamp: 'Yesterday, 11:30 AM' },
  { id: 'q-3', question: 'Show refund rates by category', timestamp: '24 Aug 2026' },
  { id: 'q-4', question: 'Compare weekend vs weekday conversion', timestamp: '20 Aug 2026' },
];
